// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/volatiletech/sqlboiler/boil"
	"todone/pkg/api/handler"
	user2 "todone/pkg/domain/service/user"
	"todone/pkg/infrastructure/mysql/user"
)

// Injectors from wire.go:

func InitUserAPI(db boil.ContextExecutor) handler.UserHandler {
	repository := user.NewUserRepoImpl(db)
	service := user2.NewUserService(repository)
	userHandler := handler.NewUserHandler(service)
	return userHandler
}
