// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/repository/board/repository.go

// Package mock_board is a generated GoMock package.
package mock_board

import (
	reflect "reflect"
	model "todone/db/mysql/model"
	repository "todone/pkg/domain/repository"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// InsertBoard mocks base method
func (m *MockRepository) InsertBoard(ctx *gin.Context, masterTx repository.MasterTx, boardData *model.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBoard", ctx, masterTx, boardData)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBoard indicates an expected call of InsertBoard
func (mr *MockRepositoryMockRecorder) InsertBoard(ctx, masterTx, boardData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBoard", reflect.TypeOf((*MockRepository)(nil).InsertBoard), ctx, masterTx, boardData)
}

// SelectByPK mocks base method
func (m *MockRepository) SelectByPK(ctx *gin.Context, masterTx repository.MasterTx, id int) (*model.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByPK", ctx, masterTx, id)
	ret0, _ := ret[0].(*model.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByPK indicates an expected call of SelectByPK
func (mr *MockRepositoryMockRecorder) SelectByPK(ctx, masterTx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByPK", reflect.TypeOf((*MockRepository)(nil).SelectByPK), ctx, masterTx, id)
}

// SelectByUserID mocks base method
func (m *MockRepository) SelectByUserID(ctx *gin.Context, masterTx repository.MasterTx, userID int) (model.BoardSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByUserID", ctx, masterTx, userID)
	ret0, _ := ret[0].(model.BoardSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByUserID indicates an expected call of SelectByUserID
func (mr *MockRepositoryMockRecorder) SelectByUserID(ctx, masterTx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByUserID", reflect.TypeOf((*MockRepository)(nil).SelectByUserID), ctx, masterTx, userID)
}

// SelectAll mocks base method
func (m *MockRepository) SelectAll(ctx *gin.Context, masterTx repository.MasterTx) (model.BoardSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", ctx, masterTx)
	ret0, _ := ret[0].(model.BoardSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll
func (mr *MockRepositoryMockRecorder) SelectAll(ctx, masterTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockRepository)(nil).SelectAll), ctx, masterTx)
}
