// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"todone/pkg/api/handler/project"
	"todone/pkg/api/handler/user"
	project4 "todone/pkg/api/usecase/project"
	user4 "todone/pkg/api/usecase/user"
	"todone/pkg/domain/repository"
	project3 "todone/pkg/domain/service/project"
	user3 "todone/pkg/domain/service/user"
	project2 "todone/pkg/infrastructure/mysql/project"
	user2 "todone/pkg/infrastructure/mysql/user"
)

// Injectors from wire.go:

func InitProjectAPI(masterTxManager repository.MasterTxManager) project.Server {
	projectRepository := project2.New(masterTxManager)
	service := project3.New(projectRepository)
	interactor := project4.New(masterTxManager, service)
	server := project.New(interactor)
	return server
}

func InitUserAPI(masterTxManager repository.MasterTxManager) user.Server {
	userRepository := user2.New(masterTxManager)
	service := user3.New(userRepository)
	interactor := user4.New(masterTxManager, service)
	server := user.New(interactor)
	return server
}
