// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"todone/pkg/api/handler/project"
	project4 "todone/pkg/api/usecase/project"
	project3 "todone/pkg/domain/service/project"
	project2 "todone/pkg/infrastructure/mysql/project"

	"github.com/volatiletech/sqlboiler/boil"
)

// Injectors from wire.go:

func InitProjectAPI(db boil.ContextExecutor) project.Server {
	repository := project2.New(db)
	service := project3.New(repository)
	interactor := project4.New(service)
	server := project.New(interactor)
	return server
}
