// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Labels         string
	Projects       string
	ProjectsLabels string
	ProjectsTodos  string
	Todos          string
	TodosLabels    string
	Users          string
	UsersProjects  string
}{
	Labels:         "labels",
	Projects:       "projects",
	ProjectsLabels: "projects_labels",
	ProjectsTodos:  "projects_todos",
	Todos:          "todos",
	TodosLabels:    "todos_labels",
	Users:          "users",
	UsersProjects:  "users_projects",
}
