// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Labels", testLabelsUpsert)

	t.Run("Projects", testProjectsUpsert)

	t.Run("ProjectsLabels", testProjectsLabelsUpsert)

	t.Run("ProjectsTodos", testProjectsTodosUpsert)

	t.Run("Todos", testTodosUpsert)

	t.Run("TodosLabels", testTodosLabelsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("UsersProjects", testUsersProjectsUpsert)
}
