// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Boards", testBoardsUpsert)

	t.Run("Cards", testCardsUpsert)

	t.Run("Kanbans", testKanbansUpsert)

	t.Run("Labels", testLabelsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("UsersBoards", testUsersBoardsUpsert)
}
