# github secretsに以下の値の登録してください
# - GCP_PROJECT_ID: gcpのprojectのid
# - GCP_SA_EMAIL  : gcpのサービスアカウントのemail
# - GCP_SA_KEY    : gcpサービスアカウントのkey_file(json)をbase64エンコーディングした文字列 `$ cat *.json | base64`

# Deploy テスト、ビルド、デプロイを自動で行う
# トリガー: masterへのpush、merge
name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    services:
    # testにmysqlが必要なので
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todone
    steps:

    # set go version
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # Create env files
    - name: Create .env file
      run: |
        cp .env_example .env
        cp sqlboiler_example.toml sqlboiler.toml

    # Run ddl
    - name: Setup DB tables
      run: |
        echo "mysqld: ALL: allow" > /etc/hosts.allow
        sudo mysql.server restart
        mysql --protocol=tcp -u root -ppassword -e"FLUSH HOSTS"
        mysql --protocol=tcp -u root -ppassword todone < ./db/mysql/ddl/ddl.sql

    # install packages
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    
    # run test
    - name: Test
      run: go test -v ./...

    # build
    - name: Build
      run: go build -v ./cmd/main.go ./cmd/wire_gen.go 

  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    # https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: GCP authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: GAE deploy
        run: |
          gcloud app deploy app.yaml --quiet
